# https://docs.github.com/en/actions/learn-github-actions/contexts

name: docker-publish

on:
  workflow_dispatch:

env:
  DOCKER_REPO: simplxs/signerserver
  GITHUB_REPO: Simplxss/SignerServer

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish-dockerhub:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download All Artifact
        uses: actions/download-artifact@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: user/app:latest