# https://docs.github.com/en/actions/learn-github-actions/contexts

name: "release"

on:
  push:
    tags:
      - "*"

permissions: write-all

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download All Artifact
        uses: actions/download-artifact@v4

      - name: Zip Artifact
        run: |
          zip -r SignerServer-windows-x64.zip SignerServer-windows-latest-x64.zip/*
          zip -r SignerServer-ubuntu-x64.zip SignerServer-ubuntu-latest-x64.zip/*
          zip -r SignerServer-ubuntu-arm64.zip SignerServer-ubuntu-latest-arm64.zip/*
      
      - name: Create Release Draft and Upload Artifacts
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body_path: CHANGELOG.md
          files: |
            SignerServer-windows-x64.zip
            SignerServer-ubuntu-x64.zip
            SignerServer-ubuntu-arm64.zip
